import { update_overlay, on_overlay_click } from "./lib/overlay.js";
import { MediaPlayer } from "./lib/libvlc.js";
import { isOPFSSupported, getCachedOPFSFile } from "./lib/opfs.js";

let vlc_options = "";

const showCanvas = new CustomEvent('toggleCanvas', { detail: { files: true } });
const hideCanvas = new CustomEvent('toggleCanvas', { detail: { files: false } });

async function init(): Promise<void> {
  const app = document.getElementById('app')!;
  const stack = document.getElementById('stack');
  const spinner = document.getElementById('spinner-lds')!;
  const pOverlay = document.getElementById("p-overlay")!;
  const playButton = document.getElementById("play-button")!;
  const bottomBar = document.getElementById("bottom-bar")!;
  const volume = document.getElementById("volume")!;
  const progressVolume = document.getElementById("bottom-progress-volume")!;
  const options = document.getElementById("opts") as HTMLInputElement;
  const reloadBtn = document.getElementById('reload')!;
  const resetBtn = document.getElementById('reset-options')!;
  const buttonBarPlayButton = document.getElementById('bottom-bar-play-button-svg')!;
  const nextChapter = document.getElementById('next-chapter')!;
  const previousChapter = document.getElementById('previous-chapter')!;
  const chapterButtons = document.getElementById('chapter-buttons')!;

  void stack; // unused but retained for future use

  document.getElementById('canvas')!.addEventListener('contextmenu', (e: Event) => e.preventDefault());

  reloadBtn.addEventListener('click', () => {
    window.location.reload();
  });

  resetBtn.addEventListener('click', () => {
    localStorage.setItem('options', '--codec=webcodec --aout=emworklet --avcodec-threads=1');
    reloadBtn.click();
  });

  options.value = localStorage.getItem('options') ?? '--codec=webcodec --aout=emworklet --avcodec-threads=1';

  options.addEventListener('change', () => {
    localStorage.setItem('options', options.value);
  });

  pOverlay.addEventListener('mouseenter', () => {
    if (window.files && window.files.length) {
      playButton.classList.remove('eject-svg');
      playButton.classList.remove('hide-button');
      bottomBar.classList.remove('hide-bottom-bar');
      chapterButtons.classList.remove('hide-chapters');
    }
  });

  pOverlay.addEventListener('mouseleave', () => {
    if (window.files && window.files.length) {
      playButton.classList.add('hide-button');
      bottomBar.classList.add('hide-bottom-bar');
      chapterButtons.classList.add('hide-chapters');
    }
  });

  volume.addEventListener('mouseenter', () => {
    progressVolume.classList.remove('hide-volume');
  });

  volume.addEventListener('mouseleave', () => {
    progressVolume.classList.add('hide-volume');
  });

  body.addEventListener('isLoading', (event: Event) => {
    const detail = (event as CustomEvent<{ isLoading: boolean }>).detail;
    if (detail.isLoading) {
      spinner.style.display = 'block';
      app.style.display = 'none';
    }

    if (!detail.isLoading) {
      spinner.style.display = 'none';
      app.style.display = 'block';
    }
  });

  body.addEventListener('toggleCanvas', (event: Event) => {
    const detail = (event as CustomEvent<{ files: boolean }>).detail;
    if (detail.files) {
      chapterButtons.classList.remove('hide-chapters');
      playButton.classList.remove('eject-svg');
      playButton.classList.remove('hide-button');
      playButton.innerHTML = '<div><svg><path d="M15.562 8.1L3.87.225c-.818-.562-1.87 0-1.87.9v15.75c0 .9 1.052 1.462 1.87.9L15.563 9.9c.584-.45.584-1.35 0-1.8z"></path></svg></div>';
      buttonBarPlayButton.innerHTML = '<path d="M15.562 8.1L3.87.225c-.818-.562-1.87 0-1.87.9v15.75c0 .9 1.052 1.462 1.87.9L15.563 9.9c.584-.45.584-1.35 0-1.8z"></path>';
      buttonBarPlayButton.classList.remove('bottom-bar-eject-button-svg');
      playButton.click();
    } else {
      chapterButtons.classList.add('hide-chapters');
      playButton.innerHTML = '<div><svg><path d="M7.27 1.047a1 1 0 0 1 1.46 0l6.345 6.77c.6.638.146 1.683-.73 1.683H1.656C.78 9.5.326 8.455.926 7.816L7.27 1.047zM.5 11.5a1 1 0 0 1 1-1h13a1 1 0 0 1 1 1v1a1 1 0 0 1-1 1h-13a1 1 0 0 1-1-1v-1z"/></div></svg>';
      playButton.classList.add('eject-svg');
      buttonBarPlayButton.innerHTML = '<path d="M15,290.01h270c8.284,0,15-6.716,15-15s-6.716-15-15-15H15c-8.284,0-15,6.716-15,15   S6.716,290.01,15,290.01z"/><path d="M15,210.01h270c0.006-0.001,0.013-0.001,0.02,0c8.285,0,15-6.716,15-15c0-3.774-1.394-7.223-3.695-9.859   L161.746,15.682c-2.845-3.583-7.17-5.672-11.746-5.672c-4.576,0-8.901,2.088-11.746,5.672l-135,170   c-3.58,4.508-4.265,10.666-1.762,15.85C3.995,206.716,9.244,210.01,15,210.01z"/>';
      buttonBarPlayButton.classList.add('bottom-bar-eject-button-svg');
    }
  });

  try {
    // VlcModule is a function generated by emscripten in experimental.js,
    // that loads the wasm file and generates a module object from it.
    // VlcModuleExt is an object defined in 'lib/module-loader.js' with a
    // bunch of options; also, all the fields of VlcModuleExt are added to
    // the returned Module.
    window.Module = await initModule(VlcModuleExt);
    createHandlers();
    localStorage.setItem('valid-options', options.value);
  } catch (e) {
    const err = e as Error;
    console.error('VLC.js initialization failed:', err);
    const validOptions = localStorage.getItem('valid-options');
    if (validOptions) {
      localStorage.setItem('options', validOptions);
    }
    // Show error to user instead of reload-looping
    app.style.display = 'block';
    app.innerHTML = '<div style="text-align:center;padding:40px;color:#d32f2f;">'
      + '<h2>VLC.js failed to initialize</h2>'
      + '<pre style="text-align:left;max-width:800px;margin:20px auto;overflow:auto;background:#f5f5f5;padding:15px;border-radius:4px;">'
      + err.message + '\n\n' + (err.stack ?? '')
      + '</pre>'
      + '<button onclick="location.reload()" style="padding:10px 20px;cursor:pointer;">Retry</button>'
      + '</div>';
  }
}

function createHandlers(): void {
  window.onerror = function(): void {
    // TODO: do not warn on ok events like simulating an infinite loop or exitStatus
    window.Module.setStatus('Exception thrown, see JavaScript console');
    body.dispatchEvent(isNotLoading);
    // Mark VLC's WASM state as unrecoverable. A function signature mismatch or
    // other WASM RuntimeError leaves internal locks and call stacks corrupted —
    // any subsequent VLC call (including play/pause/seek) will deadlock.
    // The only safe recovery is a full page reload.
    window._vlcException = true;

    // Auto-fallback: if exception fires before any frames decoded,
    // the webcodec decoder failed to initialize. Switch to avcodec
    // (software H.264) and reload so the file can still play.
    const hasFrames = window._vlcStateCache && window._vlcStateCache.timeMs > 0;
    if (!hasFrames) {
      const currentOpts = localStorage.getItem('options') ?? '';
      if (!currentOpts.includes('avcodec')) {
        // Save original options to restore after successful avcodec play
        localStorage.setItem('vlc-saved-options', currentOpts);
        localStorage.setItem('options',
          '--codec=avcodec --aout=emworklet --avcodec-threads=1');
        console.log('[vlcjs] webcodec failed early — falling back to avcodec, reloading...');
        setTimeout(() => window.location.reload(), 300);
        return;
      }
    }

    window.Module.setStatus = function(text: string): void {
      if (text) window.Module.printErr('[post-exception status] ' + text);
    };
  };

  function handleFiles(this: HTMLInputElement): void {
    // iterator in case the user selected multiple files.
    for (let i = 0; i < this.files!.length; i++) {
      const name = this.files!.item(i)!.name;
      console.log("opened file: ", name);
      window.Module['vlc_access_file'][1] = this.files!.item(i)!;
    }

    window.files = this.files;

    if (this.files && this.files.length) {
      body.dispatchEvent(showCanvas);

      // OPFS: use a previously cached copy for faster seeking if one exists.
      // Background copying during playback is deliberately avoided — writing
      // to OPFS while VLC is active interferes with Emscripten's ASYNCIFY
      // event dispatch at end-of-stream and causes a permanent page freeze.
      // Files are cached passively: the next time the same file is selected
      // after a previous session cached it, the fast OPFS-backed File is used.
      const originalFile = this.files.item(0)!;
      if (isOPFSSupported()) {
        getCachedOPFSFile(originalFile).then((cached) => {
          if (cached) {
            console.log("OPFS: using cached file for faster seeking");
            window.Module['vlc_access_file'][1] = cached;
          }
          // No background copy — avoids event-loop interference during playback.
        });
      }
    } else {
      body.dispatchEvent(hideCanvas);
    }
  }

  const inputElement = document.getElementById("fpicker_btn") as HTMLInputElement;
  inputElement.addEventListener("change", handleFiles);

  let media_player: MediaPlayer;
  const options_input = document.getElementById("opts") as HTMLInputElement;
  vlc_options = localStorage.getItem('options') ?? options_input.value;
  console.log("vlc.js: starting vlc.js with : " + vlc_options);
  const vlc_opts_array = vlc_options.split(' ');

  let vlc_opts_size = 0;
  for (let i = 0; i < vlc_opts_array.length; i++) {
    vlc_opts_size += vlc_opts_array[i].length + 1;
  }

  const buffer = window.Module._malloc(vlc_opts_size);
  let wrote_size = 0;
  for (let i = 0; i < vlc_opts_array.length; i++) {
    window.Module.writeAsciiToMemory(vlc_opts_array[i], buffer + wrote_size, false);
    wrote_size += vlc_opts_array[i].length + 1;
  }

  const vlc_argv = window.Module._malloc(vlc_opts_array.length * 4 + 4);
  const view_vlc_argv = new Uint32Array(
    window.Module.wasmMemory.buffer,
    vlc_argv,
    vlc_opts_array.length
  );

  wrote_size = 0;
  for (let i = 0; i < vlc_opts_array.length; i++) {
    view_vlc_argv[i] = buffer + wrote_size;
    wrote_size += vlc_opts_array[i].length + 1;
  }

  window.Module._wasm_libvlc_init(vlc_opts_array.length, vlc_argv);
  media_player = new MediaPlayer(window.Module, "emjsfile://1");
  media_player.set_volume(80);

  window.Module._set_global_media_player(media_player.media_player_ptr);
  window.media_player = media_player;
  window.on_overlay_click = on_overlay_click;
  window.update_overlay = update_overlay;

  update_overlay();

  // RAF loop: drive progress bar and UI state at ~4 Hz.
  // Also:
  //  - polls get_length() every ~2s until video duration is known
  //  - detects natural video end (timeMs stops advancing) to reset _vlcIsPlaying
  let _lastUIUpdate = 0;
  let _lastTimeMs = -1;
  let _staleCount = 0;
  let _lengthPollTick = 0;    // counts 250ms ticks; poll every 8 = ~2s
  let _lengthKnown = false;   // stop polling once we have a valid length

  function _uiLoop(): void {
    const now = performance.now();
    if (now - _lastUIUpdate >= 250) {
      update_overlay();
      _lastUIUpdate = now;
      _lengthPollTick++;

      // ── Duration polling ────────────────────────────────────────────────
      // get_length() reads a cached value in VLC's player struct. It is safe
      // ONLY during steady-state playback — NOT during init or EOS cleanup,
      // when vlc_player_Lock may be held by VLC threads causing ASYNCIFY
      // deadlock. Guards:
      //   _lengthPollTick >= 4  → wait ~1s after playback starts
      //   timeMs > 1000         → decoder is warmed up, not at tick 0
      //   _staleCount === 0     → not in EOS cleanup phase (frames still live)
      if (!_lengthKnown && window._vlcIsPlaying &&
          window._vlcStateCache &&
          window._vlcStateCache.timeMs > 1000 &&   // not at init (tick 0)
          _staleCount === 0 &&                       // not in EOS cleanup
          _lengthPollTick >= 4 &&                    // ≥1s since play started
          _lengthPollTick % 8 === 0) {               // every ~2s
        try {
          const len = Number(media_player.get_length());
          if (len > 0) {
            window._vlcStateCache.lengthMs = len;
            _lengthKnown = true;
          }
        } catch(e) { /* lock contended — retry next cycle */ }
      }

      // ── Restore webcodec options after successful avcodec fallback ─────────
      // If we fell back to avcodec and playback is working (>3s), restore the
      // original webcodec options so the next session tries webcodec first.
      if (!_lengthKnown && window._vlcIsPlaying &&
          window._vlcStateCache && window._vlcStateCache.timeMs > 3000) {
        const savedOpts = localStorage.getItem('vlc-saved-options');
        if (savedOpts) {
          console.log('[vlcjs] avcodec fallback successful — restoring webcodec for next session');
          localStorage.setItem('options', savedOpts);
          localStorage.removeItem('vlc-saved-options');
        }
      }

      // ── EOS fallback: set duration from last known frame time ─────────────
      // If get_length() never succeeded (rare), derive approximate duration
      // from the final frame's timestamp when EOS is detected below.
      if (window._vlcIsPlaying && window._vlcStateCache &&
          !_lengthKnown && _staleCount >= 5 &&
          window._vlcStateCache.timeMs > 0) {
        window._vlcStateCache.lengthMs = window._vlcStateCache.timeMs + 100;
        _lengthKnown = true;
      }

      // ── End-of-stream detection ──────────────────────────────────────────
      // timeMs stopped advancing → video ended naturally.
      // Reset _vlcIsPlaying to prevent blocking VLC WASM calls from button
      // clicks after EOS (they would ASYNCIFY-deadlock on vlc_player_Lock).
      if (window._vlcIsPlaying && window._vlcStateCache) {
        const currentTimeMs = window._vlcStateCache.timeMs;
        if (currentTimeMs > 0 && currentTimeMs === _lastTimeMs) {
          _staleCount++;
          if (_staleCount >= 6) { // ~1.5s of stale time
            window._vlcIsPlaying = false;
            _staleCount = 0;
          }
        } else {
          _lastTimeMs = currentTimeMs;
          _staleCount = 0;
        }
      }
    }
    requestAnimationFrame(_uiLoop);
  }
  requestAnimationFrame(_uiLoop);

  // Debounce timer for seek commands sent to VLC.
  // Rapid scrubbing updates the cache instantly for smooth visual feedback
  // but only sends the actual set_position() call to VLC after the user
  // pauses for 150ms — prevents spamming vlc_player_Lock and deadlocking.
  let _seekTimer: ReturnType<typeof setTimeout> | null = null;

  // Helper: immediately write a new position to the cache so the playhead
  // moves the instant the user seeks, without waiting for the next frame.
  function _applySeek(newPos: number): void {
    // Immediate visual feedback — update cache before any VLC call.
    const cache = window._vlcStateCache;
    if (cache) {
      cache.position = newPos;
      if (cache.lengthMs > 0) {
        cache.timeMs = Math.round(newPos * cache.lengthMs);
        // Gate pre-seek frames so they don't overwrite this feedback.
        window._vlcPendingSeekMs = cache.timeMs;
      }
    }
    // Reset stale detection so a seek near the end doesn't falsely trigger EOS.
    _lastTimeMs = -1;
    _staleCount = 0;
    update_overlay();

    // Skip the actual VLC seek if the WASM state is corrupted.
    // Cache/overlay are already updated above for visual feedback.
    if (window._vlcException) return;

    // Debounce the actual VLC seek command (set_position acquires
    // vlc_player_Lock). Rapid scrubbing would spam the lock and risk
    // ASYNCIFY deadlock. Only send the command after 150ms of inactivity.
    if (_seekTimer !== null) clearTimeout(_seekTimer);
    _seekTimer = setTimeout(() => {
      _seekTimer = null;
      media_player.set_position(newPos);
    }, 150);
  }

  const playButton = document.getElementById('play-button')!;
  const bPlayButton = document.getElementById('bottom-play-button')!;

  // Track playing state in window._vlcIsPlaying to avoid calling
  // libvlc_media_player_is_playing() on the main thread (it acquires
  // vlc_player_Lock → pthread_cond_timedwait → blocks main thread → abort).
  window._vlcIsPlaying = false;

  function handlePlayPause(): void {
    if (window.files) {
      if (window._vlcIsPlaying) {
        // set_pause(1) instead of pause() — avoids audio drain deadlock.
        if (!window._vlcException) media_player.set_pause(1);
        window._vlcIsPlaying = false;
      } else {
        // If VLC threw a WASM exception, its internal state is corrupted and
        // any VLC call will deadlock. Reload for a clean slate.
        if (window._vlcException) {
          window.location.reload();
          return;
        }
        media_player.play();
        window._vlcIsPlaying = true;
        // Reset position cache so the progress bar returns to the beginning.
        // Setting timeMs = 0 also suppresses the stale-detection loop while
        // VLC reinitialises after EOS — the guard `currentTimeMs > 0` means
        // stale detection won't fire when timeMs is 0, giving VLC time to
        // deliver its first frame without _vlcIsPlaying being killed early.
        if (window._vlcStateCache) {
          window._vlcStateCache.timeMs = 0;
          window._vlcStateCache.position = 0;
        }
        window._vlcPendingSeekMs = 0;
        _lastTimeMs = -1;
        _staleCount = 0;
        if (_seekTimer !== null) { clearTimeout(_seekTimer); _seekTimer = null; }
      }
    } else {
      inputElement.click();
    }
  }

  playButton.addEventListener('click', handlePlayPause);
  bPlayButton.addEventListener('click', handlePlayPause);

  const volumeSvgWrapper = document.getElementById('volume-svg-wrapper')!;
  volumeSvgWrapper.addEventListener('click', function(): void {
    if (!window.files || !window.files.length || window._vlcException) return;
    media_player.toggle_mute();
    update_overlay();
  });

  const progressTotal = document.getElementById('bottom-progress')!;

  // ── Drag-scrub state ─────────────────────────────────────────────────────
  // _isScrubbing: local flag driving mouse/touch event routing.
  // window._vlcIsScrubbing: global flag read by module-loader to gate
  //   incoming frame position updates during an active drag.
  let _isScrubbing = false;
  let _wasPlayingBeforeScrub = false;
  // Shorter debounce during drag for responsiveness (vs 150ms at rest).
  const SCRUB_SEEK_DELAY_MS = 80;

  // Compute a [0, 1] position from a clientX coordinate relative to the bar.
  function _posFromClientX(clientX: number): number {
    const rect = progressTotal.getBoundingClientRect();
    return Math.max(0, Math.min(1, (clientX - rect.left) / rect.width));
  }

  function _scrubStart(clientX: number): void {
    if (!window.files || !window.files.length) return;
    _isScrubbing = true;
    window._vlcIsScrubbing = true;
    _wasPlayingBeforeScrub = window._vlcIsPlaying;

    // Pause playback so seeking doesn't race with active decode.
    if (window._vlcIsPlaying && !window._vlcException) {
      media_player.set_pause(1);
      window._vlcIsPlaying = false;
    }

    _applySeek(_posFromClientX(clientX));
  }

  function _scrubMove(clientX: number): void {
    if (!_isScrubbing) return;
    const pos = _posFromClientX(clientX);

    // Immediate visual feedback: update cache directly.
    const cache = window._vlcStateCache;
    if (cache) {
      cache.position = pos;
      if (cache.lengthMs > 0) {
        cache.timeMs = Math.round(pos * cache.lengthMs);
        window._vlcPendingSeekMs = cache.timeMs;
      }
    }
    _lastTimeMs = -1;
    _staleCount = 0;
    update_overlay();

    // Debounced VLC seek (shorter window during drag).
    if (window._vlcException) return;
    if (_seekTimer !== null) clearTimeout(_seekTimer);
    _seekTimer = setTimeout(() => {
      _seekTimer = null;
      media_player.set_position(pos);
    }, SCRUB_SEEK_DELAY_MS);
  }

  function _scrubEnd(clientX: number): void {
    if (!_isScrubbing) return;
    _isScrubbing = false;
    window._vlcIsScrubbing = false;

    const finalPos = _posFromClientX(clientX);

    // Cancel any pending debounced seek and do an immediate final seek.
    if (_seekTimer !== null) { clearTimeout(_seekTimer); _seekTimer = null; }

    if (!window._vlcException) {
      media_player.set_position(finalPos);
    }

    // Update cache with final position.
    const cache = window._vlcStateCache;
    if (cache) {
      cache.position = finalPos;
      if (cache.lengthMs > 0) {
        cache.timeMs = Math.round(finalPos * cache.lengthMs);
        window._vlcPendingSeekMs = cache.timeMs;
      }
    }
    _lastTimeMs = -1;
    _staleCount = 0;
    update_overlay();

    // Resume playback if it was playing before the scrub started.
    if (_wasPlayingBeforeScrub && !window._vlcException) {
      media_player.set_pause(0);
      window._vlcIsPlaying = true;
    }
  }

  // ── Mouse drag handlers ──────────────────────────────────────────────────
  progressTotal.addEventListener('mousedown', (e: MouseEvent) => {
    e.preventDefault(); // prevent text-selection cursor
    _scrubStart(e.clientX);
  });

  function _onMouseMove(e: MouseEvent): void { _scrubMove(e.clientX); }
  function _onMouseUp(e: MouseEvent): void   { _scrubEnd(e.clientX); }

  document.addEventListener('mousemove', _onMouseMove);
  document.addEventListener('mouseup',   _onMouseUp);

  // ── Touch drag handlers ──────────────────────────────────────────────────
  progressTotal.addEventListener('touchstart', (e: TouchEvent) => {
    if (e.touches.length < 1) return;
    e.preventDefault();
    _scrubStart(e.touches[0].clientX);
  }, { passive: false });

  progressTotal.addEventListener('touchmove', (e: TouchEvent) => {
    if (e.touches.length < 1) return;
    e.preventDefault();
    _scrubMove(e.touches[0].clientX);
  }, { passive: false });

  progressTotal.addEventListener('touchend', (e: TouchEvent) => {
    // changedTouches holds the touch that was lifted.
    const t = e.changedTouches[0];
    if (t) _scrubEnd(t.clientX);
  });

  const progressVolumeTotal = document.getElementById('bottom-progress-volume')!;
  progressVolumeTotal.addEventListener('click', function(event: MouseEvent): void {
    if (!window.files || !window.files.length || window._vlcException) return;
    media_player.set_volume(event.offsetX / progressVolumeTotal.clientWidth * 100);
    media_player.set_mute(0);
    update_overlay();
  });

  const nextChapterBtn = document.getElementById('next-chapter')!;
  nextChapterBtn.addEventListener('click', () => {
    if (!window.files || !window.files.length || window._vlcException) return;
    window.media_player?.next_chapter();
    update_overlay();
  });

  const previousChapterBtn = document.getElementById('previous-chapter')!;
  previousChapterBtn.addEventListener('click', () => {
    if (!window.files || !window.files.length || window._vlcException) return;
    window.media_player?.previous_chapter();
    update_overlay();
  });

  // Keyboard accessibility: activate buttons with Enter/Space
  function addKeyboardClick(element: HTMLElement): void {
    element.addEventListener('keydown', (e: KeyboardEvent) => {
      if (e.key === 'Enter' || e.key === ' ') {
        e.preventDefault();
        element.click();
      }
    });
  }

  addKeyboardClick(playButton);
  addKeyboardClick(bPlayButton);
  addKeyboardClick(volumeSvgWrapper);
  addKeyboardClick(nextChapterBtn);
  addKeyboardClick(previousChapterBtn);

  // Keyboard accessibility: seek with arrow keys on progress bar
  progressTotal.addEventListener('keydown', (e: KeyboardEvent) => {
    if (!window.files || !window.files.length) return;
    const step = e.shiftKey ? 0.1 : 0.02; // Shift = 10%, normal = 2%
    if (e.key === 'ArrowRight') {
      e.preventDefault();
      _applySeek(Math.min(1, (window._vlcStateCache?.position ?? 0) + step));
    } else if (e.key === 'ArrowLeft') {
      e.preventDefault();
      _applySeek(Math.max(0, (window._vlcStateCache?.position ?? 0) - step));
    }
  });

  // Keyboard accessibility: volume control with arrow keys
  progressVolumeTotal.addEventListener('keydown', (e: KeyboardEvent) => {
    if (!window.files || !window.files.length || window._vlcException) return;
    const step = e.shiftKey ? 20 : 5;
    if (e.key === 'ArrowRight' || e.key === 'ArrowUp') {
      e.preventDefault();
      // Use _vlcStateCache.volume NOT media_player.get_volume() for same reason.
      const vol = Math.min(100, (window._vlcStateCache?.volume ?? 80) + step);
      media_player.set_volume(vol);
      media_player.set_mute(0);
      update_overlay();
    } else if (e.key === 'ArrowLeft' || e.key === 'ArrowDown') {
      e.preventDefault();
      const vol = Math.max(0, (window._vlcStateCache?.volume ?? 80) - step);
      media_player.set_volume(vol);
      update_overlay();
    }
  });

  // ── Frame-step keyboard handler ──────────────────────────────────────────
  // `.` (Period) / Alt+ArrowRight → step one frame forward  (next_frame)
  // `,` (Comma)  / Alt+ArrowLeft  → step one frame backward (set_time)
  //
  // Frame duration is derived from the rolling FPS estimate in module-loader.ts;
  // falls back to 24 fps if no frames have been decoded yet.
  //
  // Both directions auto-pause if the player is running, so the stepped frame
  // is visible and not immediately overwritten by the next decoded frame.
  document.addEventListener('keydown', (e: KeyboardEvent) => {
    if (!window.files || !window.files.length || window._vlcException) return;

    // Ignore keypresses that are inside a text input/textarea (the options box, etc.)
    const target = e.target as HTMLElement | null;
    if (target && (target.tagName === 'INPUT' || target.tagName === 'TEXTAREA')) return;

    const isForward  = (e.key === '.' && !e.altKey) || (e.key === 'ArrowRight' && e.altKey);
    const isBackward = (e.key === ',' && !e.altKey) || (e.key === 'ArrowLeft'  && e.altKey);
    if (!isForward && !isBackward) return;

    e.preventDefault();

    // Auto-pause so the stepped frame remains visible.
    if (window._vlcIsPlaying) {
      media_player.set_pause(1);
      window._vlcIsPlaying = false;
    }

    // Frame duration in milliseconds.
    const frameDurationMs = 1000 / (window._vlcEstimatedFps ?? 24);

    if (isForward) {
      // next_frame() advances exactly one decoded frame and re-pauses.
      media_player.next_frame();
    } else {
      // Step backward by one frame duration using set_time.
      const currentMs = window._vlcStateCache?.timeMs ?? 0;
      const targetMs  = Math.max(0, currentMs - frameDurationMs);
      media_player.set_time(targetMs, false);

      // Update cache immediately for visual feedback.
      const cache = window._vlcStateCache;
      if (cache) {
        cache.timeMs = targetMs;
        if (cache.lengthMs > 0) {
          cache.position = targetMs / cache.lengthMs;
          window._vlcPendingSeekMs = targetMs;
        }
      }
      _lastTimeMs = -1;
      _staleCount = 0;
      update_overlay();
    }
  });
}

window.onload = function(): void {
  init();
};
